apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: root-sync
  namespace: config-management-system
spec:
  sourceFormat: unstructured
  git:
    repo: https://github.com/brandon-blackline/cloud-technical-library
    branch: main
    policyDir: policies
    auth: none
